/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#bbcbbb',
        'surface-bright': '#f3fcf1',
        'on-surface': '#161d17',
        'tertiary': '#98472a',
        'on-surface-variant': '#3d4a3e',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'secondary': '#006397',
        'on-primary-container': '#005027',
        'primary-fixed-dim': '#4ae183',
        'tertiary-fixed': '#ffdbd0',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#390c00',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#ebf3e8',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#92ccff',
        'on-primary-fixed': '#00210c',
        'primary': '#006d37',
        'on-secondary-container': '#00476e',
        'outline': '#6c7b6d',
        'inverse-surface': '#2b322b',
        'primary-container': '#2ecc71',
        'surface-container': '#e8f0e5',
        'background': '#f3fcf1',
        'surface': '#f3fcf1',
        'on-error': '#ffffff',
        'tertiary-container': '#ff9875',
        'secondary-container': '#5cb8fd',
        'surface-container-low': '#eef6eb',
        'tertiary-fixed-dim': '#ffb59d',
        'on-background': '#161d17',
        'inverse-primary': '#4ae183',
        'on-secondary-fixed-variant': '#004b73',
        'surface-tint': '#006d37',
        'on-primary-fixed-variant': '#005228',
        'on-secondary-fixed': '#001d31',
        'surface-container-highest': '#dce5da',
        'on-tertiary-fixed-variant': '#793015',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#6bfe9c',
        'surface-variant': '#dce5da',
        'surface-dim': '#d4dcd2',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e2ebe0',
        'on-tertiary-container': '#772e14',
        'secondary-fixed': '#cce5ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        'stack-lg': '32px',
        'container-max-width': '1280px',
        'gutter': '24px',
        'stack-sm': '8px',
        'margin': '32px',
        'unit': '8px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'label-lg': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 4px 20px rgba(44, 62, 80, 0.08)',
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
  plugins: [],
}
